/**
 * Types internal to the Medplum Expert pipeline.
 * These are NOT exposed to other agents — only the MedplumContextDocument
 * (defined in harnessState.ts) crosses the agent boundary.
 */

/**
 * SourceIndexEntry describes a single exported symbol from a Medplum source
 * package (react, react-hooks, core). Each entry is generated by the offline
 * extraction script with LLM analysis.
 */
export interface SourceIndexEntry {
  id: string;                                         // e.g. "react/ResourceForm"
  package: 'react' | 'react-hooks' | 'core';
  filePath: string;                                   // relative path within Medplum repo
  exportName: string;                                 // the exported identifier
  category: 'component' | 'hook' | 'utility' | 'context' | 'type';
  description: string;                                // LLM-generated description
  importPath: string;                                 // e.g. "@medplum/react"
  tags: string[];
}

/**
 * FhirProperty describes a single field on a FHIR resource schema.
 * Parsed directly from the Medplum OpenAPI spec — no LLM involved.
 */
export interface FhirProperty {
  description: string;
  type?: string;
  enum?: string[];
  $ref?: string;
}

/**
 * FhirSchema describes a FHIR resource or complex data type.
 */
export interface FhirSchema {
  name: string;
  description: string;
  properties: Record<string, FhirProperty>;
  required: string[];
}

/**
 * FhirSchemaIndex is the root structure of context/medplum-fhir-schemas.json.
 */
export interface FhirSchemaIndex {
  fetchedAt: string;
  specVersion: string;
  schemas: Record<string, FhirSchema>;
}
