/**
 * PipelineStatus represents the current state of the workflow.
 */
export type PipelineStatus = 'running' | 'needs_clarification' | 'done' | 'failed';

/**
 * GitHubIssue contains the essential fields from a GitHub issue webhook payload.
 */
export interface GitHubIssue {
  number: number;
  title: string;
  body: string;
  labels: string[];
}

/**
 * Subtask represents a discrete unit of work generated by the Issue Analyzer.
 */
export interface Subtask {
  title: string;
  description: string;
  acceptanceCriteria: string[];
  dependencies: string[]; // List of subtask titles this task depends on
}

/**
 * LogEntry tracks decisions and outcomes of agent interactions.
 */
export interface LogEntry {
  timestamp: string;
  agentName: string;
  decision: string;
  status: 'success' | 'failure';
}

/**
 * HarnessState is the central state object used by LangGraph nodes.
 */
export interface HarnessState {
  issue: GitHubIssue;
  subtasks: Subtask[];
  status: PipelineStatus;
  rejectionReason?: string;
  logs: LogEntry[];
}
